create table answer (
    id bigint generated by default as identity,
    date timestamp not null,
    "option_id" varchar(255) not null,
    question_id varchar(255) not null,
    research_id varchar(255) not null,
    primary key (id)
);

create table "option" (
    id varchar(255) not null,
    description varchar(255) not null,
    question_id varchar(255) not null,
    primary key (id)
);

create table question (
    id varchar(255) not null,
    description varchar(255) not null,
    multi_select boolean not null,
    research_id varchar(255) not null,
    primary key (id)
);

create table research (
    id varchar(255) not null,
    description varchar(255),
    ends_on timestamp,
    starts_on timestamp not null,
    title varchar(255) not null,
    primary key (id)
);

alter table answer add constraint FK_answer_option foreign key ("option_id") references "option";
alter table answer add constraint FK_answer_question foreign key (question_id) references question;
alter table answer add constraint FK_answer_research foreign key (research_id) references research;
alter table "option" add constraint FK_option_question foreign key (question_id) references question;
alter table question add constraint FK_question_research foreign key (research_id) references research;